### ISSUE TITLE
Create a dynamic image add-on in the homepage

### ISSUE THREAD

**Issue by shovonroy173** [shovonroy173/booking-media-client#1]
### feat: Visit Suggestion Section

> Cities you like to visit

- [ ] Create an new unaplash project
- [ ] put city as  query
- [ ] generate 3 images and description

_section to update_
![Screenshot 2024-04-13 at 02-34-52 Booking-media](https://github.com/shovonroy173/booking-media-client/assets/83116145/19dc4329-22a0-40f2-8c77-c7137008360d)

**Comment by Sanjaydoley** [comment]
If no one is working on it, could you please assign me on it
